# Generated by Django 4.0.3 on 2022-04-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('patient_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('doctor_charges', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('room_charges', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('medicine_charges', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'bill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('patient_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'diagnosis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('field', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Given',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_id', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('patient_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'given',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('medicine_id', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'medicine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurse_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nurse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('f_name', models.CharField(blank=True, db_column='F_name', max_length=20, null=True)),
                ('l_name', models.CharField(blank=True, db_column='L_name', max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('date_admission', models.DateTimeField(blank=True, null=True)),
                ('date_discharge', models.DateTimeField(blank=True, null=True)),
                ('record_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('treatment', models.CharField(blank=True, max_length=30, null=True)),
                ('future_date', models.DateTimeField(blank=True, null=True)),
                ('patient_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('doctor_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('r_type', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('nurse_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=20, null=True)),
                ('lname', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=2, null=True)),
                ('phone_no', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('doctor_id', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'treatment',
                'managed': False,
            },
        ),
    ]
